version: '3.7'
services:
  postgres:
    image: postgres:15.6-alpine3.19
    environment:
      POSTGRES_DB: smart-cards-main
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "5454"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      smart-cards:

  rabbitmq:
    image: rabbitmq:3.12.12-management
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672
    hostname: rabbitmq
    networks:
      smart-cards:
networks:
  smart-cards: